PS C:\DevAc\join\test\JoinBackend> python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, join_BE, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying authtoken.0004_alter_tokenproxy_options... OK
  Applying join_BE.0001_initial... OK
  Applying join_BE.0002_tasks_subtasks_delete_subtask...Traceback (most recent call last):
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 350, in execute
    return super().execute(query)
           ~~~~~~~~~~~~~~~^^^^^^^
sqlite3.OperationalError: near "None": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\DevAc\join\test\JoinBackend\manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "C:\DevAc\join\test\JoinBackend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line       
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\management\commands\migrate.py", line 357, in handle
    post_migrate_state = executor.migrate(
        targets,
    ...<3 lines>...
        fake_initial=fake_initial,
    )
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\migrations\executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
        state, plan, full_plan, fake=fake, fake_initial=fake_initial
    )
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\migrations\executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
        state, migration, fake=fake, fake_initial=fake_initial
    )
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\migrations\executor.py", line 255, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\migrations\migration.py", line 132, in apply
    operation.database_forwards(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.app_label, schema_editor, old_state, project_state
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\migrations\operations\fields.py", line 110, in database_forwards        
    schema_editor.add_field(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        from_model,
        ^^^^^^^^^^^
        field,
        ^^^^^^
    )
    ^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\schema.py", line 316, in add_field
    self._remake_table(model, create_field=field)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\schema.py", line 243, in _remake_table
    self.create_model(new_model)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\base\schema.py", line 505, in create_model
    self.execute(sql, params or None)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\base\schema.py", line 202, in execute
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Cyborg-s\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 350, in execute
    return super().execute(query)
           ~~~~~~~~~~~~~~~^^^^^^^
django.db.utils.OperationalError: near "None": syntax error